minimum_pre_commit_version: "4.3.0"
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: fix-byte-order-marker
        stages: [pre-commit]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-illegal-windows-names
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 65dbdb59d2f2d9c3bdc343c566821ad3319ddaa3  # frozen: v0.16.3
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 9f70dc58c23dfcca1b97af99eaeee3140a807c7e  # frozen: v1.18.2
    hooks:
      - id: mypy
        args: [src]
        pass_filenames: false
        files: ^src/.*\.pyi?$
        additional_dependencies:
          - sqlglot==30.13.0
        stages: [pre-commit]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8  # frozen: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: meta
    hooks:
      - id: check-useless-excludes
        stages: [pre-commit]
